name: Godot GUT Tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          mv -v /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/
      - name: Run GUT smoke tests
        run: |
          godot --headless \
            --path . \
            --script addons/gut/gut_cmdline.gd \
            -- -d res://test/smoke -r tap
