name: Godot GUT Tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run GUT smoke tests
        run: |
          godot -d -s --path "$PWD" addons/gut/gut_cmdln.gd -gdir=res://test/smoke

