name: Godot GUT Tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Godot 4.4
        uses: paulloz/godot-action@v1.2.2
        with:
          version: 4.4    # major.minor (will install latest 4.4.x)
          mono: false    # or true if you need the Mono build
          export-templates: true

      - name: Run GUT smoke tests
        run: |
          godot --headless \
            --path . \
            --script addons/gut/gut_cmdline.gd \
            -- -d res://test/smoke -r tap
